### ISSUE TITLE
'tuple' object is not callable - error while running the search method

### ISSUE THREAD

**Issue by ArchitMukherjee** [BitSecret/FGPS#1]
I am trying to run FGPS search method as mentioned in the readme file, but I am getting the error:

`'tuple' object is not callable`

Here is a screenshot of the error:
![image](https://github.com/BitSecret/FGPS/assets/103459930/7a846c72-0073-45b9-9545-d6eaf148a0ce)

Please look into it and let me know how to solve it. Thankyou.

**Comment by BitSecret** [comment]
The reason for this error is that I incorrectly called the `func_timeout` function (line 94). The correct way to write it should be:

    solved, seqs = func_timeout(args.timeout, searcher.search)

**Comment by BitSecret** [comment]
I fix this bug in commit `7e5d457db23f06575899bb605351b3e503b065b1`.
