### ISSUE TITLE
ImportError: cannot import name 'get_solution_step' from 'formalgeo.tools'

### ISSUE THREAD

**Issue by ArchitMukherjee** [BitSecret/FGPS#2]
I am unable to run the interactive problem solving as mentioned in the readme file.

the error is: `ImportError: cannot import name 'get_solution_step' from 'formalgeo.tools'`

I have attached a screenshot
![image](https://github.com/BitSecret/FGPS/assets/103459930/e22ba61f-be98-4580-86b0-c9cb775ad1e6)

Please let me know how to resolve this issue. Thankyou

**Comment by BitSecret** [comment]
In version 0.0.3, formalgeo removed `get_solution_step`，remove its import:

    from formalgeo.tools import get_solution_hypertree, get_theorem_dag

Delete line 72 and 73:

    save_json(get_solution_step(solver.problem),
        os.path.join(path_logs, "run/problems/{}_{}_step.json".format(dataset_name, pid)))

**Comment by BitSecret** [comment]
I fix this bug in commit `7e5d457db23f06575899bb605351b3e503b065b1`.
